CREATE TABLE IDIOMA (
        
    DESIGNACION VARCHAR(50),
    NIVELMINIMO VARCHAR(50),
    NIVELRECOMENDADO VARCHAR(50),
    PRIMARY KEY (DESIGNACION)  
);
CREATE TABLE MASTERES( 
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1,INCREMENT BY 1),
    CODIGOPLAN INTEGER,
	NOMBRE VARCHAR(50) NOT NULL ,
	DESCRIPCION VARCHAR(2048),
	PRECIOAPROXIMADO INTEGER,
	PRESENCIALIDAD VARCHAR(50),	
	DOBLETITULACION BOOLEAN, 
	GHOMOLOGADO BOOLEAN,
	GRADO VARCHAR(100),
	IDIOMAPRINCIPAL VARCHAR(50) NOT NULL,
	IDIOMASECUNDARIO VARCHAR(50), 
    LPROGPRINCIPAL VARCHAR(50),
    LPROGSECUNDARIO VARCHAR(50), 
    CCOORDINACION VARCHAR(1024),
	PRIMARY KEY (ID),
	FOREIGN KEY(IDIOMAPRINCIPAL) REFERENCES IDIOMA(DESIGNACION),
	FOREIGN KEY(IDIOMASECUNDARIO) REFERENCES IDIOMA(DESIGNACION)
);

CREATE TABLE COLABORACION (
        
    ENTIDAD VARCHAR(100),
    PAIS VARCHAR(100),
    IDMASTER INTEGER,
    DESCRIPCION VARCHAR(1024),
    PRIMARY KEY (ENTIDAD,IDMASTER),
    FOREIGN KEY(IDMASTER) REFERENCES MASTERES(ID)
);
CREATE TABLE CURSO (
    NUMERACION INTEGER,   
    MESINICIO INTEGER,
    MESFIN INTEGER,
    CREDITOS INTEGER,
    MASTER INTEGER,
    PRIMARY KEY (NUMERACION, MASTER),
    FOREIGN KEY(MASTER) REFERENCES MASTERES(ID)
);

